### PR TITLE
university and school names

### PR DESCRIPTION
**Pull request by wulfharth7**
I've created a basic generator for the issue #255, I think it has room to improve, but I'll take a look later when I have time. I tried to code it in an hour because I was excited lol.

### CODE REVIEW

**Comment by wulfharth7** [comment]
yes sure, in an hour I'll do it and update it. thanks for your comment :)

also do you think the project is a bit messy? i think it can be improved, are you open for pr like that?

i may add more data btw while I'm updating it. fyi.

**Comment by brianvoe** [comment]
Im not looking for any big changes right now.

As far as data well take it one pr at a time

**Comment by wulfharth7** [comment]
> Im not looking for any big changes right now.
> 
> As far as data well take it one pr at a time

First time contributing in a open-source project so I was excited, I'm still a student, I've added some data, updated the readme and added customized function. 

Enjoy :D

**Comment by brianvoe** [comment]
Ok thanks. before i merge this in i have to figure why your pr looks like it's changing the whole file for the readme and lookup addition. Those two are like 3 line changes and github sees it as a full file changes. are you formatting it and changing it somehow?

**Comment by brianvoe** [comment]
Screenshot 2023-11-02 at 10 12 25 AM

Example of someone making a simple change and it not showing the whole file changing.

**Comment by brianvoe** [comment]
Screenshot 2023-11-02 at 10 14 44 AM

I cant merge this in until we figure this out. What IDE are you using? If anything revert back, open it in a simple text editor make your one line changes and repush.

**Comment by wulfharth7** [comment]
I think LF line endings has turned into CRLF somehow, im fixing it now and pushing again soon.

**Pull request closed without merging**
