### PR TITLE
fix issue with *time.Time struct fields

### LINKED ISSUE #260: time.Time pointers in structs yield zero values or nil
### Issue
Using `*time.Time` as a struct field type is handy when you want to have nullable datetimes in structs that are marshaled to JSON.

When using `gofakeit`, when there's a struct field that's a pointer to a `time.Time`:
1. For the untagged case, the value is the zero value
2. For the tagged case, the value is `nil`

I've opened a PR w/ a fix for consideration at https://github.com/brianvoe/gofakeit/pull/261

### Example

```go
package main

import (
	"fmt"
	"time"

	"github.com/brianvoe/gofakeit/v6"
)

type Example struct {
	CreatedAtSimple *time.Time
	CreatedAtTagged *time.Time `fake:"{date}"`
}

func main() {
	var foo Example
	gofakeit.Struct(&foo)
	fmt.Printf("CreatedAtSimple.IsZero(): %t\n", foo.CreatedAtSimple.IsZero())
	fmt.Printf("CreatedAtSimple: %s\n", foo.CreatedAtSimple.String())
	fmt.Printf("CreatedAtTagged: %s\n", foo.CreatedAtTagged)
}
```

```
CreatedAtSimple.IsZero(): true
CreatedAtSimple: 0001-01-01 00:00:00 +0000 UTC
CreatedAtTagged: <nil>
```

Playground: https://go.dev/play/p/Ai7rg-tr9Yx

### PR DESCRIPTION
**Pull request by woodb**
Closes #260 

I resolved one of the CodeClimate issues, but the one that remains appears to be from before--unless adding another `case` to that switch statement is triggering that 🤔

### CODE REVIEW

**Comment by brianvoe** [comment]
Thanks for the pr on this issue. I haven't run this for other scenarios but to me the more broader issue is the assignment of values to any field that is a pointer. Although this may solve the time.Time one it wouldn't solve it for any other pointer. 

If I was to merge in a pr like this I think we should try to tackle the more broad usage so that any pointer type could be assignable.

Let me know if you agree or disagree.

**Comment by woodb** [comment]
> Thanks for the pr on this issue. I haven't run this for other scenarios but to me the more broader issue is the assignment of values to any field that is a pointer. Although this may solve the time.Time one it wouldn't solve it for any other pointer.
> 
> If I was to merge in a pr like this I think we should try to tackle the more broad usage so that any pointer type could be assignable.
> 
> Let me know if you agree or disagree.

afaict, this one is specific to `time.Time` 🤔 

Other `struct`s or primitive types seem to work as expected as pointers here, but b/c we're handling `time.Time` structs specifically, we need to add this in for those

I defer to your judgement here though, I'm new to using this lib :) Thanks for the reply and maintaining it!

**Comment by brianvoe** [comment]
So the thing to keep in mind is people can set their own struct field types as well and those can be pointers. So as much as i want to merge your pr in I have provide a way that facilitates any potential pointer type. Otherwise ill have a bunch of redundant code. Hope that makes sense.

If you want to take a crack at that ill see about getting that pr in.

P.S. Github isnt sending me emails anymore on pr's or comments so i have no idea when you respond.

**Comment by brianvoe** [comment]
I could be wrong. This could just be effecting time.Time. I just need proof of that and ill see about getting your pr in.

**Comment by PumpkinSeed** [comment]
Side-note, it is not a good practice to use the `time.Time` as pointer, because it is a sealed immutable data type.

**Comment by PumpkinSeed** [comment]
> I'd be interested to read more about this :)

You can find an explanation [here](https://github.com/golang/go/issues/45669) under the "Working with json time.Time" section.

> rather than making a custom marshaller that looks at IsZero()

This issue will be solved in the [json v2 proposal](https://github.com/golang/go/discussions/63397).

**Comment by brianvoe** [comment]
Its plausible this could just be a time issue considering I did add specific cut out for time. I think the main part im not a fan of is the case switch that specifically does a check for "*time.Time".

**Comment by woodb** [comment]
> Its plausible this could just be a time issue considering I did add specific cut out for time. I think the main part im not a fan of is the case switch that specifically does a check for "*time.Time".

Agreed, I don't love it either, hah. I tried to avoid it but was having trouble finding a better place for it without increasing the scope/effort of the PR. It types as a `struct` but paths differently through the logic vs. a regular nested struct.

Can we think of a workaround (e.g. custom generator?) that could be used for `*time.Time` that we could just maybe document, if we don't like it? I thought about going that route but thought maybe that since `time.Time` is handled special that it might be worth including the pointer support as well

**Comment by brianvoe** [comment]
Let me think about it a little more. Hit me up next week if you dont hear back. ill try to wrap my head around it this weekend and ill see if I can get you a clean implementation.

**Review by brianvoe — APPROVED** [review]

**Comment by brianvoe** [comment]
I got it in a clean it up a little but I think im ok with this for now.

**Comment by woodb** [comment]
Thanks for taking the time over the weekend to work on this @brianvoe 🙌 Much appreciated!

I looked at the cleanups, they look great! Thanks for that, too. Cheers!

**Comment by brianvoe** [comment]
No problem, enjoy!

**Pull request merged**
