### PR TITLE
Feat/future date

### PR DESCRIPTION
**Pull request by hound672**
Resolve: https://github.com/brianvoe/gofakeit/issues/245

### CODE REVIEW

**Comment by brianvoe** [comment]
super close! instead of test i use example so that way the doc has a usage example and examples can be used for tests as well. If you want to keep your test thats fine just be sure to add an example.

**Comment by brianvoe** [comment]
setting a seed should do it. every other function has an example, this should be the same. If your having issues try to setup it up as close as possible like the others and show me the code and ill help you figure out the rest of the way.

**Comment by hound672** [comment]
I mean `FutureDate` at first calls `time.Now()` and then adds to it random duration.
So every `FutureDate` result will higher than the previous one.
Due to that I'm not able to write constant string in output example.
I pushed another one commit with example but without output string.

**Comment by brianvoe** [comment]
ah i see the issue. Let me think about this one and see if i can come up with an answer for you

**Comment by brianvoe** [comment]
v6.23.0

**Pull request merged**
