### PR TITLE
fuzz Regex

### PR DESCRIPTION
**Pull request by xiegeo**
Saw issue #219 and thought to get a go at it. Regex was a good target for fuzz and a cool feature I'm looking forward to using.

It found 3 classes of bugs so far:

- ^ or $ at unexpected places. No legal output is possible so special errors need to be returned.
- \b and \A, perhaps more? Maybe unimplemented?
- A capture group followed by a large repeat might run out of memory.

If Regex is only expected to take trusted input, then not all bugs found by fuzz are worth fixing, just filtering out the "bugs" at the start of fuzz is good enough. Perhaps it needs a check regex function that is more strict than regexp.Compile?

### CODE REVIEW

**Comment by xiegeo** [comment]
Fuzz is falling on build because the go version is too low. Since fuzz is just a test dependency, only the fuzz test file needs to be version guarded. I'm going to do that. But until the build script adds newer versions of go, fuzz tests will be completely ignored.

@brianvoe What is the plan on supporting different go versions for this project?

**Comment by brianvoe** [comment]
Sorry for not responding earlier. I needed to think this one through a little.

So i really like your approach here. Going after regex is a good usage for fuzz testing. As far as a fix I would be open to an obvious fix that if someone put something in and it ran forever and basically broke the app then lets figure that out and get a fix in. I'm pretty good at regex but not an expert by any means. So Ill have to rely on others to help me figure a fix.

For Fuzzing in general I like the idea of adding it but I dont want to add the test data and make the repo larger. I think we can get away with identifying issues through the fuzz test and then append examples to static testing.

As far as supported versions. I try to at least support back a handful of versions. If fuzzing breaks that even though its only in tests then I might push fuzzing until more versions become available.

Let me know your thoughts. Thanks!

**Comment by xiegeo** [comment]
> For Fuzzing in general I like the idea of adding it but I dont want to add the test data and make the repo larger. I think we can get away with identifying issues through the fuzz test and then append examples to static testing.

Yes, that's the best way to maintain regression tests for issues. The testdata directory is just a repository for issues found and not yet fixed. They should be turned into unit tests after fixed.

> As far as supported versions. I try to at least support back a handful of versions. If fuzzing breaks that even though its only in tests then I might push fuzzing until more versions become available.

This problem should be fixed now that the fuzz test is ignored on lower go versions. Can you approve the workflow and give it a try?

**Comment by brianvoe** [comment]
I like where your head is with this. The only issue I see is we cant throw a panic. Gofakeit cant ever be the reason to take an app down. It needs to either silently stop and return an empty string or a string with the error in it. or update regex to allow a return error as a secondary param return. But that would be compatibility. It's a tough call and I don't really know the answer.

**Comment by brianvoe** [comment]
I guess I would rather just give them an empty string if they give us a regex that cant possibly finish or actually create anything. That would be the only avenue I see for this challangee.

**Comment by xiegeo** [comment]
@brianvoe It no longer panics now (still does so internally, but recovered). Is there anything else blocking a merge or just need more time to consider?

**Comment by brianvoe** [comment]
v6.20.0

**Pull request merged**
