### PR TITLE
Small tweaks, tests, fixes and optimizations

### PR DESCRIPTION
**Pull request by bgadrian**
Added seed to some benchmarks, so they can be compared.
Small refactor and optimization (+10%) of ReplaceWith* functions
Added Digit() function
Fixed RandString panic when input is empty
Optimized ShuffleStrings (20%)
Fixed getRandValue, intDataCheck and dataCheck panic when input is empty

### CODE REVIEW

**Comment by bgadrian** [comment]
I didn't noticed but rand.Shuffle was added in Go 1.10, what solution do you prefer? 

1. Duplicate the algorithm in the package, keeping backward compatibility
2. bump the Go minimum version to 1.10

**Comment by brianvoe** [comment]
So ive been able to keep go 1.0 compatible due to a good amount of people who use it on lower versions. So i dont know if its a deal breaker for you but I would like to keep it that way.

**Comment by bgadrian** [comment]
The Codeclimate issue is harder to fix, because of the map[]map[map] ... one is Int one is String.

**Comment by brianvoe** [comment]
I hate to put another deal breaker on you but i do also maintain a 100% code coverage for this package as well.

**Comment by bgadrian** [comment]
No worries, I did not noticed that I missed something.

As a side note, it is strange to strive for 100% coverage but not having unit tests, examples just cover the basic cases.

**Comment by bgadrian** [comment]
One more question, how did you generated the BENCHMARKS.md ? I want to update it in my next PR that has some more optimizations.

**Comment by brianvoe** [comment]
go test -bench=. -benchmem

**Comment by brianvoe** [comment]
Examples are tests. 😄

**Comment by bgadrian** [comment]
I meant the markdown https://raw.githubusercontent.com/brianvoe/gofakeit/master/BENCHMARKS.md 
not the benchmark results. The default output has tabs or json not markdown tables

**Comment by bgadrian** [comment]
Ok thanks, It seems to works with https://www.tablesgenerator.com/markdown_tables (copy pasting the CLI output), I will update the benchmarks in the next PR tomorrow. 

For this one is there anything else left to do?

**Comment by brianvoe** [comment]
code climate has two simple things its asking you to update. should be easy
https://codeclimate.com/github/brianvoe/gofakeit/pull/35

**Comment by bgadrian** [comment]
Well I just moved away some code to trick the linter, unfortunately having duplicate code is a must, without generics is the only clean/performance way to do it, at least I could not found a nice way to combine to a single function check of 2 nested maps keys.

**Comment by brianvoe** [comment]
Thanks and nice job!

**Pull request merged**
