### PR TITLE
improve address descriptions

### PR DESCRIPTION
**Pull request by se-omar**

### CODE REVIEW

**Comment by brianvoe** [comment]
@se-omarayman Ok i just realized i forgot to say something about these descriptions. I think one of the things i was trying to stay away from the repeating certain parts. I was trying to see if we could go more the route of not including generate or random in the sentence as they are already givens

Example:
Set of fields including street, city, state, zip code, country, latitude, and longitude
Name of a city
Full name of a country

Let me know if that makes sense or if you disagree

**Comment by se-omarayman** [comment]
Hmm, i think i agree.
having the full sentence "generates a random full name" is more of a complete and coherent sentence than "full name" but most of it is useless info.
if I'm using the library i want to quickly see what random **X** does it generate so i only care about the **X**

**Comment by se-omarayman** [comment]
but looking at a [faker-js sample](https://github.com/faker-js/faker/blob/next/src/modules/animal/index.ts) and a [faker-python sample](https://github.com/joke2k/faker/blob/master/faker/providers/color/__init__.py) they use some form of "Generate a random X" for a more coherent sentence i guess

**Comment by brianvoe** [comment]
I updated animal to give you an idea of what i was thinking
https://github.com/brianvoe/gofakeit/blob/develop/animal.go

**Comment by brianvoe** [comment]
I agree if the description is something like "Pet name" adding "Generate random pet name" fills out the sentence more but i threw this into chatgpt to help and i was able to get some better wording outputs. so for pet name it gave me. "A petname is a special, affectionate nickname given to someone you care about deeply." I took that and simplified it to "Affectionate nickname given to a pet"

**Comment by brianvoe** [comment]
"Affectionate nickname given to a pet" > "Generate random pet name"

**Comment by se-omarayman** [comment]
so i guess if I'm using the library like ```gofakeit.CarMaker()``` , there is no need to say in the description that it generates a car maker, but it's better to describe any special cases the function has or what a car maker is.
so the description for car maker is "A large industrial facility with assembly lines for producing cars".

check the [updated descriptions](https://github.com/se-omarayman/gofakeit/blob/car-descriptions/car.go) for Car and let me know

**Comment by brianvoe** [comment]
I think you see my thoughts on this pretty well. I wish i had the answers for each scenario. Let me try to do car maker and see what you think.

Prompt: i need a description of the definition of "car maker" (with previous prompts saying no more than 15 words)
Output: A car maker is a company that designs, manufactures, and sells automobiles.
Adjustment: Company name that designs, manufactures, and sells automobiles

**Comment by brianvoe** [comment]
I think your descriptions of cars is pretty good. the feedback for those would be trying to make is short and sweet. I try to do less than 10 but its its not enough no more than 15, start sentences with capital letter and I try not to start it the A. Let me know your thoughts.

I think with all that the descriptions will look so good within those parameters.

**Comment by se-omarayman** [comment]
I see, I'll finish up another category with these parameters and link it here for review

**Comment by brianvoe** [comment]
Perfect! Those look so good! I cant wait to see the rest of them. Nice job!

**Comment by brianvoe** [comment]
When you do a pr just make sure to set it to develop. sometimes i forget and it gets merged into master. there might be a setting i can set to automatically do that

**Pull request merged**
