### PR TITLE
Custom Rand and Go routine safe

### PR DESCRIPTION
**Pull request by brianvoe**

### CODE REVIEW

**Comment by brianvoe** [comment]
@rcoy-v @PumpkinSeed Let me know what you guys think.

**Comment by rcoy-v** [comment]
From my understanding, this allows the customization of random source, but still relies on an internal global state for all cases, with the `SetGlobalFaker()` and `globalFaker`. If correct, this change would not solve the originally stated issue in #78 and my PR(s). This only helps others who commented on wanting to use different sources, e.g. `crypto/rand`.

**Comment by brianvoe** [comment]
hahah ye of little faith. Of course it can do what you want. I just havent added examples yet.

**Comment by brianvoe** [comment]
@rcoy-v See faker-test.go file for examples of using New, NewCrypto and NewCustom.

**Comment by rcoy-v** [comment]
I see the receiver methods and examples now, lgtm. Are there any areas you want help refactoring?

**Comment by brianvoe** [comment]
@rcoy-v I got most the core ones. But if you want to tackle some I wont touch some files.
If you want you can tackle beer, car, emoji, food.

**Comment by rcoy-v** [comment]
Opened #135 for the suggested files.

**Comment by brianvoe** [comment]
@rcoy-v Ill be at my parents tomorrow so whatever you want to tackle is up to you. Ill try to get another round of updates in tomorrow night.

**Comment by brianvoe** [comment]
@rcoy-v I think once this is done whoever had hesitations before using gofakeit wont have a reason not to use it!!!

**Comment by PumpkinSeed** [comment]
LGTM, the only problem what I see that the PR tells that it's go routine safe, but there isn't any test which proves it. (Side note I tried it out and it is and it has a nice entropy.)

**Comment by brianvoe** [comment]
@rcoy-v I think i go it all. If you can take a look and make sure we have all the secondary tests for everything I think thats all thats left to be done.

**Comment by rcoy-v** [comment]
I added most of the missing examples and benchmarks, but ran out of time on some last few files. Test coverage is enough to quickly see what examples are missing.

As well, some of the more dynamic functions like csv and json are not going to work as expected. They are using the lookup funcs, which still use the package functions and global faker. I think the lookup functions need to be changed as well in some way, and none of those have been touched.

**Comment by brianvoe** [comment]
I tackled a couple of issues. The big one now is things like json, csv, generate and regex use lookups to run things and I havent found a good way to pass the *rand.Rand to the call yet. Ill have to try to figure that one out

**Comment by brianvoe** [comment]
@rcoy-v Merged in. Created new version v6. Thanks for all your help!!!

**Pull request closed without merging**
