### PR TITLE
add vehicle data

### PR DESCRIPTION
**Pull request by calvernaz**

### CODE REVIEW

**Comment by brianvoe** [comment]
Holy cow! Nice Job! 

First time someone was able to just jump in and add something with full examples and benchmarks with 100% coverage.

Would love to know why you needed vehicles but its so nice and perfect that ill add it just cause.

**Comment by calvernaz** [comment]
Thanks, glad to contribute.  

I use your package in a continuous feed (data generator stream) for a fleet system, so having this data makes sense for my use case.

I really appreciate this package, you've done a great job!

**Comment by brianvoe** [comment]
I bumped the repo version to v3.15.0 in case you use version control

**Comment by brianvoe** [comment]
I just notice on your vehicle list the model array is all in upper case. for consistency sake can you update that to be title case?

**Comment by calvernaz** [comment]
Alright [#38](https://github.com/brianvoe/gofakeit/pull/38)

**Pull request merged**
