### PR TITLE
generate fake data in struct arrays

### PR DESCRIPTION
**Pull request by ishando**
Add capability to populate array type elements in structs

### CODE REVIEW

**Comment by brianvoe** [comment]
I love this addition. Im going to merge this into my develop and make some slight changes(things like add a fakesize:number(otherwise random number)) and get the code coverage to be a little higher.

**Comment by ishando** [comment]
I was looking at adding one more addition to this: use `fake:"3:{firstname}"` to allow generating arrays with multiple elements for a function

what do you think?

**Comment by brianvoe** [comment]
Ya i hear ya. The thought behind having a separate tag is in the future if i need to add another tag type I wouldnt have to try to squeeze everything into a single string.

**Comment by brianvoe** [comment]
Let me know if you want to add fakesize tag or if you want me to add it

**Comment by brianvoe** [comment]
I pushed to develop if you want to add it.

**Comment by ishando** [comment]
it seems a bit overkill to have a separate tag just for the array size, unless you envision having it also used in other scenarios.
I'm not sure what the conventions/expectations are there either, but i haven't come across other modules using multiple tags.

i get that the number on its own is a bit odd/vague and have been trying to think of/find a better convention

following the validator module convention (https://godoc.org/gopkg.in/go-playground/validator.v9) one option might be;
- `'fake:"size=3,{password}"'` for an array of strings with applied function
- `'fake:"size=3"'` for an array of structs

**Pull request merged**
