### PR TITLE
add .io domain suffix

### PR DESCRIPTION
**Pull request by hbagdi**
.io is hip in the moment

### CODE REVIEW

**Comment by brianvoe** [comment]
Example tests need to be update and once those are all successful ill merge this in.

**Comment by brianvoe** [comment]
Domain effects a bunch of other data. Are you not seeing failed tests on your local machine?

**Comment by hbagdi** [comment]
@brianvoe did not use `-race` on local

**Comment by brianvoe** [comment]
Nice job! Thanks for doing the year update too. I forget that i have to update that every year.

**Pull request merged**
