### PR TITLE
feat: return error from Generate() for invalid catagory

### PR DESCRIPTION
**Pull request by hbagdi**
Breaking change:
Generate returns an error if the template is invalid

This is debatable feature and one could say that it's the caller's responsibility to provide the right string to parse.
If you plan to merge this in, I can provide tests as well.

### CODE REVIEW

**Comment by brianvoe** [comment]
I hear what you are saying. Although an error isnt valuable enough for a breaking change to the package. Ill keep it in mind if i need to do a new version of gofakeit. Thanks.

**Comment by hbagdi** [comment]
Could we maintain a `next` branch where all the breaking changes go in?
This way it's easy to keep such features ready to go whenever enough pile up.

If this sounds good, just publish a `next` branch in your repo.
I'll polish this PR and open it against this branch.

**Comment by brianvoe** [comment]
I definitely will when the time comes in which i will do a new version release but at this point I dont have anything game changing that i feel needs to pivot this package in a different direction to do a full version bump.

Ill keep you updated though.

**Comment by hbagdi** [comment]
Sounds good to me.

Thanks a lot for making this library!

**Comment by brianvoe** [comment]
Thank you for the PR's

**Pull request closed without merging**
