### PR TITLE
feat: introduce random json generation

### PR DESCRIPTION
**Pull request by hbagdi**
@brianvoe How does this look to you?

It needs a work to cover all the [valid jsons](http://www.json.org/).

Would you be willing to take this in?

### CODE REVIEW

**Comment by brianvoe** [comment]
I would be up for having this in the package. If you can get examples and benchmarks in Ill take a look and make sure everything is up to speed.

I was also thinking at some point getting struct generators in. So people could auto populate a struct of information.

**Comment by hbagdi** [comment]
@brianvoe I wish to add struct generators but it doesn't seem straightforward right now.

I'll get this PR in a good shape and then ping you.

**Comment by hbagdi** [comment]
@brianvoe 

- Tons of test cases are missing, I'll add them all soon.
- How is the method interface? Should it return a `map` (currently) or a `[]byte` representing the JSON itself? In most cases, users would be interested in the []byte representing JSON. Thoughts?

**Comment by brianvoe** [comment]
So i put a lot of time into this and have come to realize that a better path to take for this would be to build a struct generator and then they can choose to use that struct outright or to convert it into a json and use it however they need. 

If we did the struct generator path it would essentially make the json generator obsolete.

Let me know your thoughts on this.

**Comment by hbagdi** [comment]
@brianvoe 
`struct` generators will be sophisticated and could be accomplished with [struct tags](https://stackoverflow.com/questions/10858787/what-are-the-uses-for-tags-in-go).

But I don't agree that this would render JSON generator obsolete.
There could be cases where wiring up a struct would be a bit too much.
User could simply define a JSON template in a file and then run through the JSON generator to render a JSON.
Also, populating custom data types in struct will not be trivial and it will not be as **flexible** as JSON generation, since JSONs are mostly all strings.

**Comment by brianvoe** [comment]
So lets say someone wants a json set of randomly generated information.

```golang
type Info struct {
    name string `gofakeit: name.first`
    companies []string `gofakeit: company.name`
}

func main () {
    info := &Info{}
    gofakeit.populate(info)
    jsonInfo := json.marshal(info)
}
```

I find this much more powerful and closer to the go way of doing things than either creating a string to replace values (cause technically if you wanted you could do that now) or having a json file that you would load and generate a json output for.

**Comment by hbagdi** [comment]
How would you handle custom data types and data types like URLs, dates...?

https://github.com/wawandco/fako achieves what we're doing here but only with the following data types:
string, bool, int, int32, int64, float32, float64

**Comment by brianvoe** [comment]
Urls would be strings. We can also support date types. Supporting all base types are really the only thing we need.

**Comment by hbagdi** [comment]
@brianvoe We could support faking structs as well as providing JSON templating. Why would it be a bad idea to include both of these in the library?

**Comment by brianvoe** [comment]
Its not so much a bad idea as it is something people wouldnt use if they had a struct generator.

So just to visualize the json form of it
```golang
    json := `
    {
        name: {name.first} {name.last},
        company: {company.name},
        beer: {beer.name}
    }
    gofakeit.JSONString(json)
`
```

I think the map and array generators are a good idea but other than that we are just running unmarshall ad putting it into an unstructured map[string]interface{}

I am trying to see what your saying but i just need to see a really good use case and im not seeing it yet.

**Comment by hbagdi** [comment]
Well, I've a use case (and that's why I came up with this PR).
I have a JSON template stored in a file and want to generate a random JSON based on the template.

If one wants to fake structs in code, or test cases, then the tag approach is the way to go.
But if there's no need to struct or the random JSON being generated is not to be used inside Go runtime, then generating a random JSON from a template will be useful.

**Comment by brianvoe** [comment]
Well tell me what i can do to help meet you half way. I want to help facilitate your specific need.

**Comment by hbagdi** [comment]
Any possibility of getting this in? This would simplify templating JSON files and then running them through gofakeit.

**Comment by brianvoe** [comment]
I believe the new struct generator you built solves this.

**Pull request closed without merging**
