### PR TITLE
 feat: add random generators for built-in types

### PR DESCRIPTION
**Pull request by hbagdi**
@brianvoe 
Thought this would make the library one stop solution for everything.
This work will also be used in the upcoming random struct generation.
I've made good progress on it and expect to send you a PR soon.

### CODE REVIEW

**Comment by brianvoe** [comment]
Once travis is good with tests ill merge this in.

**Comment by hbagdi** [comment]
Seems like `rand.Uint64` was introduced after 1.7.
The branch compiles fine on 1.9.2.

Will fix it

**Comment by brianvoe** [comment]
Nice Job!

**Comment by brianvoe** [comment]
What project are you using this for?

**Comment by hbagdi** [comment]
@brianvoe https://github.com/hbagdi/rand in the open source world.
Need a random JSON generator based on a template!

**Pull request merged**
