### PR TITLE
Add gofakeit command

### PR DESCRIPTION
**Pull request by adambabik**
The motivation for this was using [jsonify](https://github.com/fgeller/jsonify) which allows to quickly produce JSON using CLI.

The thing with jsonify is that it does not support generating fake data, and that's good, one tool should do one thing.

gofakeit is awesome lib but the fact that you can't use it from a CLI is a bummer, hence, I decided to propose this PR. I haven't found and previous attempts to do this.

The main goals were simplicity and easy to maintenance. The exposed commands are generated using `go generate` tool. When a new function is added, it's enough to execute `go generate ./cmd/gofakeit/...` in the project root directory to update the list of available commands.

The current limitation is that it supports only functions that take no params and return a single value of type string. The codebase can be extended to support this, it's not a blocker.

### CODE REVIEW

**Comment by brianvoe** [comment]
Just to keep you updated ill be going over this and seeing if at all i can get this in. Thanks for this pr.

**Comment by brianvoe** [comment]
Can you take a look at the code climate fail and see if you can tackle what they are complaining about?
https://codeclimate.com/github/brianvoe/gofakeit/pull/69

**Comment by hbagdi** [comment]
I had plans to add this to https://github.com/hbagdi/rand but they were dropped.
We could merge both the products if needed.

**Comment by adambabik** [comment]
@brianvoe thanks!

Regarding the CodeClimate. I can definitely fix `ExportedFuncs` function but ` cmd/gofakeit/internal/execute_gen.go` should probably be ignored. This is auto-generated file with `go generate`.

**Comment by adambabik** [comment]
@brianvoe I fixed errors reported by CodeClimate except for this autogenerated file. I also added some unit tests for `ExportedFuncs` function.

**Comment by brianvoe** [comment]
Ok im going to merge this into develop. I need to make some big updates to it but ultimately i think your original pr purpose will still be there. I just want to get rid of cobra and organize a few things.

**Comment by brianvoe** [comment]
Just a heads up on this i was able to integrate a function lookup system and built out a command line mode and http server. Right now I have a specific map output that generates a map[string]interface{} that i can marshal to json and output. If you @adambabik @hbagdi could take at look at that type of output and let me know if thats enough for you and maybe some feedback on things. That would help

**Comment by adambabik** [comment]
@brianvoe it works pretty cool and meet my criteria. The only thing I would add is `--help/-h` flag which is missing.

**Comment by brianvoe** [comment]
Ill add an issue for it.

**Pull request merged**
